### ISSUE TITLE
Consider releasing 0.3.1 or 0.4?

### ISSUE THREAD

**Issue by boustrophedon** [rust-vmm/seccompiler#62]
Hi, I was wondering if you'd consider publishing a new version so that the apply_to_all_threads function is available for use in my own crate.

**Comment by andreeaflorescu** [comment]
I don't think that would be a problem. @petreeftime or @alindima can one of you do the release? If not, I can do it in a couple of days.

**Comment by alindima** [comment]
I can do 0.4.0 tomorrow

**Comment by alindima** [comment]
Let's merge this PR and I'll publish to crates.io after: https://github.com/rust-vmm/seccompiler/pull/63

**Comment by alindima** [comment]
done, v0.4.0 is available on crates.io and the releases page on github
