### ISSUE TITLE
Requirement for “signed” commits in PR template is confusing

### ISSUE THREAD

**Issue by Hawk777** [rust-vmm/seccompiler#70]
The PR template says:
> All commits in this PR are signed (with `git commit -s`)

As someone who doesn’t tend to remember which one is `-s` and which one is `-S`, I found this wording confusing: IMO the word “signed”, on its own, means cryptographically signed, i.e. `-S`; I think this is probably the more common understanding. IMO something like “signed off” would be sufficient to eliminate the confusion, though there might be other rewordings that would be even more clear.

**Comment by alindima** [comment]
The PR template is part of: https://github.com/rust-vmm/.github. Feel free to open a PR there.
Personally, I don't think it's a big deal as long as it says `git commit -s`, but I can also understand the confusion
